Pages/Clear.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QueueSystem.Pages;

public class ClearModel : PageModel
{
    private readonly QueueService _queueService;

    public string Queue { get; set; } = "";

    public ClearModel(QueueService queueService)
    {
        _queueService = queueService;
    }

    public void OnGet()
    {
        Queue = _queueService.CurrentQueue;
    }

    public void OnPost()
    {
        _queueService.Reset();
        Queue = _queueService.CurrentQueue;
    }
}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QueueSystem.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QueueSystem.Pages;

public class IndexModel : PageModel
{
    private readonly QueueService _queue;

    public IndexModel(QueueService queue)
    {
        _queue = queue;
    }

    public IActionResult OnPostGetQueue()
    {
        _queue.NextQueue();
        return RedirectToPage("Queue");
    }

    public IActionResult OnPostClear()
    {
        return RedirectToPage("Clear");
    }
}

Pages/Index1.cshtml.cs
// using Microsoft.AspNetCore.Mvc;
// using Microsoft.AspNetCore.Mvc.RazorPages;

// namespace QueueSystem.Pages;

// public class IndexModel : PageModel
// {
//     private readonly QueueService _queue;

//     public IndexModel(QueueService queue)
//     {
//         _queue = queue;
//     }

//     public IActionResult OnPostGetQueue()
//     {
//         _queue.NextQueue();
//         return RedirectToPage("Queue");
//     }

//     public IActionResult OnPostClear()
//     {
//         return RedirectToPage("Clear");
//     }
// }

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QueueSystem.Pages;

public class PrivacyModel : PageModel
{
    public void OnGet()
    {
    }
}

Pages/Queue.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Globalization;

namespace QueueSystem.Pages;

public class QueueModel : PageModel
{
    private readonly QueueService _queueService;

    public string Queue { get; set; } = "";
    public string QueueTime { get; set; } = "";

    public QueueModel(QueueService queueService)
    {
        _queueService = queueService;
    }

    public void OnGet()
    {
        Queue = _queueService.CurrentQueue;
        var dt = _queueService.LastQueueTime;
        QueueTime = string.Format(
        CultureInfo.InvariantCulture,
        "วันที่ : {0:dd/MM/yyyy}   เวลา {0:HH:mm} น.",
        dt
    );
    }
}

Pages/Clear.cshtml
@page
@model ClearModel

<div class="screen">
    <div class="header">IT 05-3</div>

    <div class="content">

        <form method="post">
            <button class="btn-sub">
                ล้างคิว
            </button>
        </form>

        <div style="text">
            หมายเลขคิวปัจจุบัน
        </div>

        <div class="queue-number">
            @Model.Queue
        </div>

        <form method="get" action="/">
            <button class="btn-sub">
                กลับไปหน้ารับบัตรคิว
            </button>
        </form>

    </div>
</div>

Pages/Index.cshtml
@page
@model IndexModel

<div class="screen">
    <div class="header">IT 05-1</div>

    <div class="content">

        <form method="post">
            <button class="btn-main" asp-page-handler="GetQueue">
                รับบัตรคิว
            </button>

            <br /><br />

            <button class="btn-sub btn-gray" asp-page-handler="Clear">
                ล้างคิว
            </button>
        </form>

    </div>
</div>

Pages/Index1.cshtml
@page
@model IndexModel

<h1>IT 05-1</h1>

<form method="post">
    <button asp-page-handler="GetQueue">รับบัตรคิว</button>
    <button asp-page-handler="Clear">ล้างคิว</button>
</form>

Pages/Queue.cshtml
@page
@model QueueModel

<div class="screen">
    <div class="header">IT 05-2</div>

    <div class="content">

        <div class="text">หมายเลขคิว</div>

        <div class="queue-number">
            @Model.Queue
        </div>

        <div class="text">
            @Model.QueueTime
        </div>

        <form method="get" action="/">
            <button class="btn-sub">
                กลับไปหน้ารับบัตรคิว
            </button>
        </form>

    </div>
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Queue System</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @RenderBody()
</body>
</html>